Repository flipt-io/flipt-client-sdks, pull requests merged in 2025-05, with the labels that each got.

#971 chore: try to build smaller libs
  .github/workflows/package-ffi-engine-android.yml
  .github/workflows/package-ffi-engine-darwin.yml
  .github/workflows/package-ffi-engine-linux.yml
  .github/workflows/package-ffi-engine-windows.yml
  Cargo.toml
  flipt-engine-ffi/build.sh
Labels: chore, size:M, lgtm

#985 chore: update golangci lint version
  .github/workflows/lint-sdks.yml
  flipt-client-dart/lib/flipt_client.dart
  flipt-client-go/benchmark_test.go
  flipt-client-go/evaluation.go
  flipt-client-go/evaluation_test.go
Labels: chore, size:S

#986 chore: finally get dart sdk working on flutter for ios
  .github/images/flutter-ios-user-defined-settings.png
  flipt-client-dart/README.md
  flipt-client-dart/ffigen.yaml
  flipt-client-dart/ios/Classes/FliptClient.h
  flipt-client-dart/ios/Classes/FliptClient.m
  flipt-client-dart/ios/flipt_client.podspec
  flipt-client-dart/lib/src/ffi/loader.dart
  flipt-client-dart/pubspec.yaml
  flipt-client-js/package.json
  flipt-client-js/tsconfig.json
Labels: size:L

#1000 feat: add the ability to get and set the snapshot in the FFI engine
  flipt-engine-ffi/src/evaluator.rs
  flipt-engine-ffi/src/http.rs
  flipt-engine-ffi/src/lib.rs
  flipt-evaluation/src/lib.rs
  flipt-evaluation/src/models/flipt.rs
  flipt-evaluation/src/store.rs
Labels: enhancement, size:L, lgtm

#1001 chore: fix js slim wasm support and update readme
  flipt-client-js/README.md
  flipt-client-js/engine.wasm.js
  flipt-client-js/package.json
Labels: documentation, size:L

#1025 Use shim for useSyncExternalStore
  flipt-client-react/README.md
  flipt-client-react/package-lock.json
  flipt-client-react/package.json
  flipt-client-react/src/useFliptClient.ts
Labels: enhancement, automerge, size:S, lgtm

#1024 feat(java): expose snapshot api
  flipt-client-java/.gitignore
  flipt-client-java/.idea/.gitignore
  flipt-client-java/.idea/gradle.xml
  flipt-client-java/.idea/misc.xml
  flipt-client-java/.idea/vcs.xml
  flipt-client-java/README.md
  flipt-client-java/build.gradle
  flipt-client-java/src/main/java/io/flipt/client/FliptEvaluationClient.java
  flipt-client-java/src/test/java/TestFliptEvaluationClient.java
  flipt-client-java/src/test/resources/empty_snapshot.json
  flipt-client-java/src/test/resources/snapshot.json
  flipt-client-python/flipt_client/models.py
  flipt-engine-ffi/Cargo.toml
  flipt-engine-ffi/build.rs
  flipt-engine-ffi/include/flipt_engine.h
  flipt-engine-ffi/src/evaluator.rs
  flipt-engine-ffi/src/lib.rs
  flipt-engine-ffi/wrapper.c
  flipt-engine-wasm-js/src/lib.rs
  flipt-engine-wasm/src/lib.rs
  flipt-evaluation/src/lib.rs
  flipt-evaluation/src/models/flipt.rs
  flipt-evaluation/src/models/mod.rs
  flipt-evaluation/src/models/snapshot.rs
  flipt-evaluation/src/models/source.rs
  flipt-evaluation/src/store.rs
  go.work.sum
Labels: enhancement, size:XXL, lgtm
