Repository flipt-io/flipt-client-sdks, pull requests merged in 2025-04, with the labels that each got.

#894 chore: add unknown operator test
  flipt-client-js/src/node/index.ts
  flipt-evaluation/src/lib.rs
Labels: automerge

#933 chore: redo wasm-pack / bundler in prep for slim
  flipt-client-js/.gitignore
  flipt-client-js/package-lock.json
  flipt-client-js/package.json
  flipt-client-js/rollup.config.js
  flipt-client-js/src/browser/index.ts
  flipt-client-js/src/node/index.ts
  flipt-client-js/tsconfig.json
  go.work.sum
  package/wasm/sdks/sdk.go
  test/main.go
Labels: chore, size:L

#946 chore: FlagType enum for Python SDK
  flipt-client-python/flipt_client/models.py
  flipt-client-python/tests/__init__.py
  flipt-client-ruby/spec/client_spec.rb
  test/fixtures/testdata/features.yml
Labels: chore, size:S, lgtm

#947 feat: Dart mobile
  flipt-client-dart/README.md
  flipt-client-dart/lib/src/flipt_evaluation_client.dart
  flipt-client-dart/pubspec.yaml
  flipt-client-go/version.go
  package/ffi/sdks/dart.go
Labels: enhancement, size:M, lgtm

#948 fix: try to fix Flutter/dart mobile support for Android
  .github/workflows/lint-sdks.yml
  flipt-client-dart/.gitignore
  flipt-client-dart/README.md
  flipt-client-dart/android/.gitkeep
  flipt-client-dart/ffi/.gitkeep
  flipt-client-dart/ffigen.yaml
  flipt-client-dart/ios/.gitkeep
  flipt-client-dart/lib/src/ffi/bindings.dart
  flipt-client-dart/lib/src/ffi/loader.dart
  flipt-client-dart/lib/src/ffi/loader_flutter.dart
  flipt-client-dart/lib/src/ffi/loader_io.dart
  flipt-client-dart/lib/src/flipt_evaluation_client.dart
  flipt-client-dart/lib/src/models.dart
  flipt-client-dart/native/.gitkeep
  flipt-client-dart/pubspec.yaml
  flipt-client-dart/test/flipt_client_test.dart
  package/ffi/sdks/dart.go
  test/main.go
Labels: enhancement, size:XL

#949 chore: package ios engine for use in dart
  .github/workflows/package-ffi-engine-ios.yml
Labels: size:L

#965 chore: try to fix flutter lib bundling
  .gitignore
  flipt-client-dart/.gitignore
  flipt-client-dart/flutter_plugin.yaml
  flipt-client-dart/pubspec.yaml
Labels: chore, size:S

#966 feat: Dart package ios
  .github/workflows/lint-sdks.yml
  .github/workflows/package-ffi-engine-darwin.yml
  flipt-client-dart/ios/flipt_client.podspec
  flipt-client-dart/lib/src/ffi/loader.dart
  flipt-client-dart/pubspec.yaml
  package/ffi/main.go
  package/ffi/sdks/dart.go
  package/ffi/sdks/sdk.go
  test/main.go
Labels: enhancement, size:L

#968 fix(js): rm path alias
  flipt-client-js/src/browser/index.ts
  flipt-client-js/src/node/index.ts
  flipt-client-js/src/slim/index.ts
  flipt-client-js/tsconfig.json
Labels: bug, size:M

#967 chore: strip the ios .a libs before dart publish
  .github/workflows/package-ffi-engine-darwin.yml
  package/ffi/sdks/dart.go
  strip_xcframework.sh
Labels: chore, size:M

#969 chore: strip ios libs when packaging
  .github/workflows/package-ffi-engine-ios.yml
  package/ffi/sdks/dart.go
  strip_xcframework.sh
Labels: chore, size:M
