Repository flipt-io/flipt-client-sdks, pull requests merged in 2025-06, with the labels that each got.

#1049 chore: add java test for invalid flipt url
  flipt-client-java/README.md
  flipt-client-java/src/main/java/io/flipt/client/FliptEvaluationClient.java
  flipt-client-java/src/main/java/io/flipt/client/models/ClientOptions.java
  flipt-client-java/src/test/java/TestFliptEvaluationClient.java
  flipt-engine-ffi/src/lib.rs
  flipt-evaluation/src/error.rs
Labels: chore, size:L

#1028 feat(kotlin): add snapshot support
  flipt-client-java/README.md
  flipt-client-kotlin-android/.editorconfig
  flipt-client-kotlin-android/README.md
  flipt-client-kotlin-android/src/androidTest/java/io/flipt/client/TestFliptEvaluationClient.kt
  flipt-client-kotlin-android/src/main/java/io/flipt/client/CLibrary.kt
  flipt-client-kotlin-android/src/main/java/io/flipt/client/FliptEvaluationClient.kt
  flipt-client-kotlin-android/src/main/java/io/flipt/client/models/ClientOptions.kt
  flipt-client-kotlin-android/src/test/resources/empty_snapshot.json
  flipt-client-kotlin-android/src/test/resources/snapshot.json
Labels: enhancement, size:L, lgtm

#1057 feat!(dart): update dart sdk for 1.0
  flipt-client-dart/README.md
  flipt-client-dart/lib/flipt_client.dart
  flipt-client-dart/lib/src/errors.dart
  flipt-client-dart/lib/src/flipt_client.dart
  flipt-client-dart/lib/src/models.dart
  flipt-client-dart/lib/src/models.g.dart
  flipt-client-dart/lib/src/plugin_registration.dart
  flipt-client-dart/pubspec.yaml
  flipt-client-dart/test/flipt_client_test.dart
Labels: enhancement, size:L

#1061 feat!(ruby): refactor for 1.0
  flipt-client-ruby/.rubocop.yml
  flipt-client-ruby/.rubocop_todo.yml
  flipt-client-ruby/Gemfile.lock
  flipt-client-ruby/README.md
  flipt-client-ruby/flipt-client-ruby.gemspec
  flipt-client-ruby/lib/flipt_client.rb
  flipt-client-ruby/lib/flipt_client/models.rb
  flipt-client-ruby/loadtest.rb
  flipt-client-ruby/spec/client_spec.rb
Labels: enhancement, size:XL

#1062 feat!(go): refactor for 1.0 + env
  flipt-client-dart/README.md
  flipt-client-go/README.md
  flipt-client-go/benchmark_test.go
  flipt-client-go/client.go
  flipt-client-go/client_test.go
  flipt-client-go/config.go
  flipt-client-go/config_test.go
  flipt-client-go/errors.go
  flipt-client-go/types.go
  flipt-client-go/version.go
  flipt-client-java/README.md
  flipt-client-python/README.md
  flipt-client-ruby/README.md
  flipt-client-swift/README.md
Labels: documentation, enhancement, size:XL

#1065 feat!(kotlin): standardize kotlin for 1.0
  flipt-client-kotlin-android/README.md
  flipt-client-kotlin-android/src/androidTest/java/io/flipt/client/TestFliptClient.kt
  flipt-client-kotlin-android/src/main/java/io/flipt/client/FliptClient.kt
  flipt-client-kotlin-android/src/main/java/io/flipt/client/FliptEvaluationClient.kt
  flipt-client-kotlin-android/src/main/java/io/flipt/client/models/ClientOptions.kt
Labels: documentation, enhancement, size:XL

#1066 chore: Update swift android test workflows
  .github/workflows/package-ffi-engine-ios.yml
  .github/workflows/test-android-sdk.yml
  .github/workflows/test-swift-sdk.yml
  flipt-client-dart/pubspec.yaml
  flipt-client-js/eslint.config.cjs
  flipt-client-kotlin-android/src/test/resources/empty_snapshot.json
  flipt-client-kotlin-android/src/test/resources/snapshot.json
  flipt-client-react/package.json
Labels: chore, size:XL

#1067 fix: Kotlin tests
  flipt-client-kotlin-android/build.gradle
  flipt-client-kotlin-android/src/androidTest/java/io/flipt/client/TestFliptClient.kt
  flipt-client-kotlin-android/src/main/cpp/fliptengine_wrapper.c
  flipt-client-kotlin-android/src/main/cpp/include/flipt_engine.h
  flipt-client-kotlin-android/src/main/java/io/flipt/client/CLibrary.kt
  flipt-client-kotlin-android/src/main/java/io/flipt/client/FliptClient.kt
  flipt-client-kotlin-android/src/main/java/io/flipt/client/models/ClientOptions.kt
  flipt-client-kotlin-android/src/test/resources/empty_snapshot.json
  flipt-client-kotlin-android/src/test/resources/snapshot.json
Labels: size:L

#1068 fix: swift client and swift ci tests
  .github/workflows/test-android-sdk.yml
  .github/workflows/test-swift-sdk.yml
  flipt-client-swift/.gitignore
  flipt-client-swift/Package.swift
  flipt-client-swift/Sources/FliptClient/FliptClient.swift
  flipt-client-swift/Sources/FliptEngineFFI.xcframework/Info.plist
  flipt-client-swift/Sources/FliptEngineFFI.xcframework/ios-arm64-simulator/Headers/module.modulemap
  flipt-client-swift/Sources/FliptEngineFFI.xcframework/ios-arm64/Headers/module.modulemap
  flipt-client-swift/Sources/FliptEngineFFI.xcframework/macos-arm64/Headers/module.modulemap
  flipt-client-swift/Sources/FliptEngineFFI.xcframework/macos-x86_64/Headers/module.modulemap
  flipt-client-swift/Tests/FliptClientTests/FliptClientTests.swift
Labels: chore, size:L

#1069 chore!(dart): rm macos x86 support to decrease file size
  flipt-client-dart/README.md
  flipt-client-dart/lib/src/ffi/loader.dart
  flipt-client-dart/pubspec.yaml
  package/ffi/sdks/dart.go
Labels: chore, size:S

#1070 feat(js): add flipt v2 env support
  flipt-client-js/src/browser/index.ts
  flipt-client-js/src/core/types.ts
  flipt-client-js/src/node/index.ts
  flipt-client-js/src/slim/index.ts
Labels: enhancement, size:M, lgtm

#1071 feat!(react): add env support and move namespace to options
  flipt-client-react/README.md
  flipt-client-react/package-lock.json
  flipt-client-react/package.json
  flipt-client-react/src/provider.test.tsx
  flipt-client-react/src/provider.tsx
  flipt-client-react/src/useFliptClient.ts
Labels: documentation, enhancement, automerge, size:M

#1108 fix: added serde to WASMResponse.error_message in flipt-engine-wasm
  flipt-engine-wasm-js/src/lib.rs
Labels: bug, size:XS, lgtm

#1110 fix(js): use correct type for evaluate context
  flipt-client-js/src/core/base.ts
  flipt-client-js/src/core/types.ts
Labels: bug, size:XS, lgtm

#1131 fix: python time delta serialization
  flipt-client-python/flipt_client/models.py
  go.work.sum
Labels: bug, size:XS

#1133 feat: add TLS configuration support to FFI engine
  flipt-client-js/package.json
  flipt-engine-ffi/src/http.rs
  flipt-engine-ffi/src/lib.rs
  flipt-engine-ffi/src/testdata/localhost.crt
  flipt-engine-ffi/src/testdata/localhost.key
  flipt-engine-wasm/src/lib.rs
  release/README.md
Labels: enhancement, size:L, lgtm

#1134 Feat: python tls support
  flipt-client-python/README.md
  flipt-client-python/flipt_client/models.py
  flipt-client-python/tests/test_flipt_client.py
  flipt-engine-ffi/src/http.rs
  test/fixtures/tls/ca.crt
  test/fixtures/tls/ca.key
  test/fixtures/tls/generate_certs.sh
  test/fixtures/tls/server.crt
  test/fixtures/tls/server.key
  test/main.go
Labels: enhancement, size:L

#1135 feat: add TLS configuration support to Java SDK
  flipt-client-java/README.md
  flipt-client-java/src/main/java/io/flipt/client/FliptClient.java
  flipt-client-java/src/main/java/io/flipt/client/models/ClientOptions.java
  flipt-client-java/src/main/java/io/flipt/client/models/TlsConfig.java
  flipt-client-java/src/test/java/TestFliptClient.java
  flipt-client-python/flipt_client/models.py
  flipt-engine-ffi/src/http.rs
  flipt-engine-ffi/src/lib.rs
  test/main.go
Labels: documentation, enhancement, size:L, lgtm

#1136 feat: add TLS configuration support to Ruby SDK
  flipt-client-ruby/Gemfile.lock
  flipt-client-ruby/README.md
  flipt-client-ruby/lib/flipt_client.rb
  flipt-client-ruby/lib/flipt_client/models.rb
  flipt-client-ruby/spec/client_spec.rb
  test/main.go
Labels: documentation, enhancement, automerge, size:L, lgtm

#1137 feat: add TLS configuration support to C# and Dart SDKs
  flipt-client-csharp/README.md
  flipt-client-csharp/src/FliptClient/Models/ClientOptions.cs
  flipt-client-csharp/src/FliptClient/Models/TlsConfig.cs
  flipt-client-csharp/tests/FliptClient.Tests/FliptClientTests.cs
  flipt-client-dart/README.md
  flipt-client-dart/lib/src/models.dart
  flipt-client-dart/lib/src/models.g.dart
  flipt-client-dart/test/flipt_client_test.dart
  test/main.go
Labels: documentation, enhancement, automerge, size:XL, lgtm

#1138 feat: add TLS configuration support to Go SDK
  flipt-client-go/README.md
  flipt-client-go/client_test.go
  flipt-client-go/config.go
  test/main.go
Labels: enhancement, automerge, size:L

#1126 refactor(js): remove unnecessary calls
  flipt-client-js/src/core/base.ts
Labels: chore, size:S
